name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy Jekyll site with Docker
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: docker run --name -v /var/www/kb-nfdi4microbiota/:/srv/jekyll/_site jekyll_N4M jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"