name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Jekyll site with Docker
        run: docker run --name kb_jekyll jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Copy site data from Docker container
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: docker cp kb_jekyll:/srv/jekyll/_site/* /var/www/kb-nfdi4microbiota/

      - name: Clean created image
        run: docker remove -f kb_jekyll